[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "amscrot-py"
dynamic = ["version"]
description = "AmSC Resource Orchestration Client Toolkit"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["AmSC Resource Orchestration Toolkit", "Fabfed Framework", "Cloud", "FABRIC", "Chameleon", "MOC"]
license = {text = "MIT License"}
authors = [
  {name = "Abdelilah Essiari", email = "aessiari@lbl.gov"},
  {name = "Ezra Kissel", email = "kissel@es.net"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fabrictestbed-extensions",
    "python-chi==0.17.11",
    "sense-o-api==1.42",
    "ansible==9.5.1",
    "ansible-runner==2.3.6",
    "xmltodict",
    "boto3",
    "google-cloud-compute",
    "pydantic",
    "paramiko==4.0.0",
    "esnet-iri==1.0.0.post1",
    "nersc-iri==1.0.0",
    "kubernetes==35.0.0"
]

[project.urls]
Homepage = "https://github.com/esnet/amsc-isro-toolkit"

[project.scripts]
amscrot = "tools.cli:main"
fabfed = "tools.cli:main"

[tool.setuptools.dynamic]
version = {attr = "amscrot.__VERSION__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]

[tool.setuptools.package-data]
amscrot = ["**/*.json", "**/*.yml", "**/*.j2"]
