# Fabric
# https://portal.fabric-testbed.net
# Create and download FABRIC at https://portal.fabric-testbed.net/ via Experiments -> Manage Tokens
# Create a Bastion Key and User FABRIC at https://portal.fabric-testbed.net/ via Experiments -> Manage SSH Keys
fabric:
   bastion-user-name:
   token-location:
   bastion-key-location: 
   project_id: 
   slice-private-key-location:
   slice-public-key-location:

# Chameleon
# https://www.chameleoncloud.org/
# Create a CLI Password as described here: https://chameleoncloud.readthedocs.io/en/latest/technical/cli.html
#
# ProjectName can be found here.
# See https://chi.tacc.chameleoncloud.org/identity/
# See https://chi.uc.chameleoncloud.org/project/

# Chameleon has different project ids for CHI@TACC and CHI@UC. These can be found in uc and tacc
# opendstack rc files.  
# See https://chi.tacc.chameleoncloud.org/project/api_access/openrc/
# See https://chi.uc.chameleoncloud.org/project/api_access/openrc/

# ProjectName can be found here. It usually starts with CH.
# See https://chi.tacc.chameleoncloud.org/identity/
# See https://chi.uc.chameleoncloud.org/project/

# It is best to have same keypair for CHI@TACC and CHI@UC
# See https://chi.tacc.chameleoncloud.org/project/key_pairs/
# See https://chi.uc.chameleoncloud.org/project/key_pairs/
chi:
   project_name:
   key_pair:        # keypair name
   user:
   password:
   slice-private-key-location:
   slice-public-key-location:
   project_id:
     tacc:
     uc:

# https://sense-o.es.net:8443/StackV-web/portal/
sense:
   auth_endpoint: https://sense-o.es.net:8543/auth/realms/StackV/protocol/openid-connect/token
   api_endpoint: https://sense-o-dev.es.net:8443/StackV-web/restapi
   client_id: StackV
   username:
   password:
   secret:
   verify: False
   slice-private-key-location:    # THIS IS NEEDED IF USING JANUS SERVICE


janus:
   url:
   username:
   password:
   token:

# Cloudlab
# https://cloudlab.us
#
# see https://www.cloudlab.us/ssh-keys.php to upload ssh public key.
#
# Certificate. 
# see https://www.cloudlab.us/getsslcert.php
# Must download certificate and decrypt using openssl command below.
# and reference the cloudlab-decrypted.pem below
#
# >openssl rsa -in  cloudlab.pem > cloudlab-decrypted.pem 
# >openssl x509 -in  cloudlab.pem >> cloudlab-decrypted.pem 

cloudlab:
  project:
  certificate:      # decrypted pem file. See above for instructions
  user:
  slice-private-key-location:
  
# Amazon AWS
aws:
   access_key:
   secret_key:

# Google Cloud
# Create a service account and downdload it to the path below
gcp:
   service_key_path:
   project:
